language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: iaH07MJqkCy24dYIi4wlirNK83B7oDMKUTfnf/9XSpM3ajaQJEG7xMQV3QBq6nrHwf13BxAOrexiCxFGwxu2ekf5K7IlTnlV/ZaZpRNAfWkL2CGKFIaP8PZAq4YcCGVxz2gBrNz7/tofnAi5EvijqpxM8V5cGEH5Ei+d+bn2PKzCvmsXfyNnT82n9pI/NGC5duQ8ygBLVka0AlxA5UuQU+a2wA5cweaiwg27A0Ln8K32kZiIUTb1K7c9Gw2B28OPEMZGkpuG9MSxKUK004U/DlT3SdwYMoxn8bYS5OqpmtiL8iz5J0lFkWFwc24tl06PTWty9ZwBrVRY4uhpMITtlUVFTIxuGCrqtxqPuYUiePKu0PLZrfcmR4dcK4PGAL6r3wUlxmnYSCel1sRNvUNdUf2pL/3Ym3RH6jb4pJzW0KZfC31uvncb887Jikp1/8MMnNA4U3A+8wfjSrrmckmfMXyKa7bCCoBLcpE946pUSjTQvE2PYivAXRXFiWvXbBjhYlb5ki9CaKp8H264VE1PSUZTZHcjd6tDZi+vmaNbrCmZwkHijgdYKkqZvDLS1/ryXZ+FtnSNgMGy0JPX5i2c0bAfCHQLc2KYX+A+uhh7OGIQAvCBC53ruJgACZdIG47T2cZVujLx5u3cZyPeVUJI47jGv37ha0UABR0/E2VeMJM=
